spring:
  application:
    name: msservice
  redis:
    host: YOUR-IP
    port: 6379
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.h2.Driver
    username: ms
    password: ms
    #    url: jdbc:mysql://YOUR-IP:12306/ms?characterEncoding=utf-8&useSSL=false
    url: jdbc:h2:tcp://localhost:9092/~/ms;IFEXISTS=TRUE;SCHEMA=ms
  rabbitmq:
    host: YOUR-IP
    port: 5672
    username: admin
    password: admin
  cloud:
    consul:
      host: YOUR-IP
      port: 8500
      discovery:
        heartbeat:
          enabled: true
        health-check-interval: 5s
        health-check-url: http://tolo.free.idcfengye.com/actuator/health
        health-check-critical-timeout: 5s
        prefer-ip-address: true
        ip-address: 127.0.0.1
  zipkin:
    base-url: http://YOUR-IP:9411
  sleuth:
    sampler:
      probability: 1
server:
  port: 8085
feign:
  hystrix:
    enabled: true
logging:
  level:
    org.springframework.cloud.openfeign: debug
