spring:
  application:
    name: orderservice
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ms
#    password: ms
#    url: jdbc:mysql://YOUR-IP:12306/ms?characterEncoding=utf-8&useSSL=false
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
      driver-class-name: org.h2.Driver
      password: ms
      type: com.alibaba.druid.pool.DruidDataSource
#      url: jdbc:mysql://YOUR-IP:12306/ms?characterEncoding=utf-8&useSSL=false
      url: jdbc:h2:tcp://localhost:9092/~/ms;IFEXISTS=TRUE;SCHEMA=ms
      username: ms
    filters: stat,wall,log4j
    initialSize: 5
    maxActive: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM DUAL
  rabbitmq:
    host: YOUR-IP
    port: 5672
    username: admin
    password: admin
  cloud:
    consul:
      host: YOUR-IP
      port: 8500
      discovery:
        heartbeat:
          enabled: true
        health-check-interval: 5s
        health-check-url: http://tolo.free.idcfengye.com/actuator/health
        health-check-critical-timeout: 5s
        prefer-ip-address: true
        ip-address: 127.0.0.1
  zipkin:
    base-url: http://YOUR-IP:9411
  sleuth:
    sampler:
      probability: 1
server:
  port: 8081
feign:
  hystrix:
    enabled: true
logging:
  level:
    org.springframework.cloud.openfeign: debug
