spring:
  application:
    name: redisservice
  redis:
    host: YOUR_IP
    port: 6379
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.h2.Driver
    username: ms
    password: ms
    #    url: jdbc:mysql://YOUR_IP:12306/ms?characterEncoding=utf-8&useSSL=false
    url: jdbc:h2:tcp://localhost:9092/~/ms;IFEXISTS=TRUE;SCHEMA=ms
  cloud:
    consul:
      host: YOUR_IP
      port: 8500
      discovery:
        health-check-interval: 5s
        health-check-url: http://tolo.free.idcfengye.com/actuator/health
        health-check-critical-timeout: 5s
        prefer-ip-address: true
        ip-address: 127.0.0.1
        heartbeat:
          enabled: true
  zipkin:
    base-url: http://YOUR_IP:9411
  sleuth:
    sampler:
      probability: 1
server:
  port: 8084
feign:
  hystrix:
    enabled: true
logging:
  level:
    org.springframework.cloud.openfeign: debug
